version: "3"
services:
  mongo:
    container_name: mevnstack_mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    env_file:
      - .env
  server:
    container_name: mevnstack_backend
    image: chadsparrow/mevn_stack:backend-prod
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mongo:27017
volumes:
  mongodbdata:
