FROM node:8.9.4

ENV NODE_ENV="development"

RUN apt-get update -qq
RUN apt-get install -y build-essential
RUN apt-get install -y git

WORKDIR /usr/src/app/server

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5000

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD /wait && npm run dev
